image: node:8.1.1

pipelines:
  default:
    - step:
        script: 
          - yarn install
          - yarn run build
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
