image: node:8.1

pipelines:
  default:
    - step:
        script: 
          - npm install
          # npm start
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
