image: node:7.10

pipelines:
  default:
    - step:
        script: 
          - npm install
          - npm test
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
