image: node:7.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - npm install
          - npm start
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
